### Import data

In [71]:
import pandas as pd

In [72]:
data = pd.read_csv('data.csv')

In [73]:
data.head()

Timestamp  \
0  11/25/2024 14:41   
1  11/25/2024 14:44   
2  11/25/2024 14:49   
3  11/25/2024 14:49   
4  11/25/2024 14:49   

  How many hours on average of sleep do you get on a typical school/workday?  \
0                                                  9                           
1                                                  7                           
2                                                  6                           
3                                                  8                           
4                                                  8                           

   How would you rate your overall stress level in the past month?  \
0                                                  3                 
1                                                  2                 
2                                                  5                 
3                                                  2                 
4                                                  1                 

  How many days in a week do you feel overwhelmed or anxious due to academic responsibilities?  \
0                                                  7                                             
1                                                  0                                             
2                               Around 5 days a week                                             
3                                                  2                                             
4                                                  0                                             

  How many times per week do you engage in physical exercise (e.g., walking, running, sports)?  \
0                                                  1                                             
1                                                  5                                             
2                                                  0                                             
3                                         5-6 times                                              
4                                                  3                                             

  How many hours per week do you spend completing assignments or projects?   \
0                                                  3                          
1                                                 40                          
2                              Around 4 hours a week                          
3                                           10 hours                          
4                                                  1                          

  How many exams or tests do you typically have in a month?  \
0                                                  3          
1                                               0.56          
2                                                  4          
3                                              3-Feb          
4                                                  1          

   How would you describe the difficulty level of your current coursework?  \
0                                                  3                         
1                                                  2                         
2                                                  5                         
3                                                  2                         
4                                                  1                         

   How many times a week do you feel that academic deadlines are unmanageable?    \
0                                                NaN                               
1                                                NaN                               
2                                                NaN                               
3                                                NaN                               
4                                               

In [74]:
data.describe()

How would you rate your overall stress level in the past month?  \
count                                         169.000000                 
mean                                            3.189349                 
std                                             1.068880                 
min                                             1.000000                 
25%                                             2.000000                 
50%                                             3.000000                 
75%                                             4.000000                 
max                                             5.000000                 

       How would you describe the difficulty level of your current coursework?  \
count                                         169.000000                         
mean                                            3.189349                         
std                                             1.005760                         
min                                             1.000000                         
25%                                             3.000000                         
50%                                             3.000000                         
75%                                             4.000000                         
max                                             5.000000                         

       How many times a week do you feel that academic deadlines are unmanageable?    \
count                                                0.0                               
mean                                                 NaN                               
std                                                  NaN                               
min                                                  NaN                               
25%                                                  NaN                               
50%                                                  NaN                               
75%                                                  NaN                               
max                                                  NaN                               

       Score  
count    0.0  
mean     NaN  
std      NaN  
min      NaN  
25%      NaN  
50%      NaN  
75%      NaN  
max      NaN

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 11 columns):
 #   Column                                                                                        Non-Null Count  Dtype  
---  ------                                                                                        --------------  -----  
 0   Timestamp                                                                                     169 non-null    object 
 1   How many hours on average of sleep do you get on a typical school/workday?                    169 non-null    object 
 2   How would you rate your overall stress level in the past month?                               169 non-null    int64  
 3   How many days in a week do you feel overwhelmed or anxious due to academic responsibilities?  167 non-null    object 
 4   How many times per week do you engage in physical exercise (e.g., walking, running, sports)?  168 non-null    object 
 5   How many hours per week do yo

### drop column

In [76]:
dropped_column = data.columns[[0, -3, -2]]
dropped_column

Index(['Timestamp',
       'How many times a week do you feel that academic deadlines are unmanageable?  ',
       'Score'],
      dtype='object')

In [77]:
data = data.drop(dropped_column, axis=1)
data

How many hours on average of sleep do you get on a typical school/workday?  \
0                                                    9                           
1                                                    7                           
2                                                    6                           
3                                                    8                           
4                                                    8                           
..                                                 ...                           
164                                                  8                           
165                                                  7                           
166                                                  8                           
167                                                6.5                           
168                                                  7                           

     How would you rate your overall stress level in the past month?  \
0                                                    3                 
1                                                    2                 
2                                                    5                 
3                                                    2                 
4                                                    1                 
..                                                 ...                 
164                                                  3                 
165                                                  3                 
166                                                  3                 
167                                                  3                 
168                                                  3                 

    How many days in a week do you feel overwhelmed or anxious due to academic responsibilities?  \
0                                                    7                                             
1                                                    0                                             
2                                 Around 5 days a week                                             
3                                                    2                                             
4                                                    0                                             
..                                                 ...                                             
164                                                  5                                             
165                                                  2                                             
166                                                  2                                             
167                                                  5                                             
168                                                  2                                             

    How many times per week do you engage in physical exercise (e.g., walking, running, sports)?  \
0                                                    1                                             
1                                                    5                                             
2                                                    0                                             
3                                           5-6 times                                              
4                                                    3                                             
..                                                 ...                                             
164                                                  6                                             
165                                                  4                                             
166                                                  

In [78]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 8 columns):
 #   Column                                                                                        Non-Null Count  Dtype 
---  ------                                                                                        --------------  ----- 
 0   How many hours on average of sleep do you get on a typical school/workday?                    169 non-null    object
 1   How would you rate your overall stress level in the past month?                               169 non-null    int64 
 2   How many days in a week do you feel overwhelmed or anxious due to academic responsibilities?  167 non-null    object
 3   How many times per week do you engage in physical exercise (e.g., walking, running, sports)?  168 non-null    object
 4   How many hours per week do you spend completing assignments or projects?                      169 non-null    object
 5   How many exams or tests do you typica

In [79]:
phrase_to_number = {
    'usually none': 0,
    'maybe not': 0,
    'không ngày nào': 0,
    'rarely any': 0,
    'none': 0,
    'No time for such things': 0,
    'cả ngày': 1,
    'once a week': 1,
    'twice a week': 2,
    'Monday to friday (walking)': 5,
    'every day': 7,
    'the whole week': 7,
    'everyday of the week': 7,
    'all week': 7,
    'everyday': 7,
    'all': 7,
    'I just walk around the campus. About an hour a day': 7,
    'yes but not to much ': 1,
    'idk': 0,
    'walking': 0
}

### rename column

In [80]:
data = data.rename(columns = {data.columns[0]: 'sleep_time',
                       data.columns[1]: 'stress_level',
                       data.columns[2]: 'stress_days_per_week',
                       data.columns[3]: 'exe_day_per_week',
                       data.columns[4]: 'assignment_hour_per_week',
                       data.columns[5]: 'num_exams_month',
                       data.columns[6]: 'difficulty_level',
                       data.columns[7]: 'hours_spend_projects'})

### Necessary function

In [124]:
def scaling_for_days(value):
    if value < 0:
        return 0
    
    if value > 7:
        return 7
    
    return value


def scaling_for_hours_week(value):
    if value < 0:
        return 0
    
    if value > 7*24:
        return 7*24
    
    return value


def scaling_for_exams_month(value):
    if value < 0:
        return 0
    
    if value > 36:
        return 36
    
    return value

In [ ]:
import numpy as np

phrase_to_number = {
    'usually none': 0,
    'maybe not': 0,
    'không ngày nào': 0,
    'rarely any': 0,
    'none': 0,
    'No time for such things': 0,
    'cả ngày': 1,
    'once a week': 1,
    'twice a week': 2,
    'Monday to friday (walking)': 5,
    'every day': 7,
    'the whole week': 7,
    'everyday of the week': 7,
    'all week': 7,
    'everyday': 7,
    'all': 7,
    'I just walk around the campus. About an hour a day': 7,
    'yes but not to much ': 1,
    'idk': 0,
    'walking': 0,
    '2hours/day': 14,
    'once every week': 1,
    'an exam every 2 weeks': 0.5,
    'one to none': 0.5,
    'depends': None,
    'depend': None,
    'almost none': 0,
    'assignments every week': 1,
    'only mid term': 1,
    'one': 1,
    'rarely': 0,
    'all the time': 7,
    'sometimes': 0.5,
    'maybe once a week': 1,
    'usually 3-4 days': 3.5,
    'maybe 3-4': 3.5,
    'on weekdays': 5,
    'on weekends': 2,
    'hardly ever': 0,
    'every weekend': 2,
    'a few times': 0.5,
    
    'Depends': None,
    "I don't get the point of the question, its the same with above question": None,
    "I don't get this question": None,
    'variety': None,
    'Unsure': None,
    'Not much really': None,
    "We don't have academic deadlines right now": None,
    "I don't know": None,
    "i don't knwo": None,
    'minimum 60 hours per week': 60,
    'More than 40 hours/week': 40,
    'all the time': 7,
    'every other day': 3.5,
    'most days': 5,
    'once in a while': 0.5,
    'barely ever': 0,
    'not much': 0,
    'over a week': 7,
    'around the clock': 7
}


### How many hours on average of sleep do you get on a typical school/workday?

In [82]:
data['sleep_time'].unique()

array(['9', '7', '6', '8', '5', '4', '6-7 hours', '6 hour', '7-8 hours',
       '3 hous/day', '6h ', '5 to 6', '4-5 hours', '8 hours', '6h',
       '6-8 hours', '5 or 6 hours', '7-Jun', '25', '7 to 8 ', '3',
       '5-7 hours', '6-May', '5-Apr', '4 hours', '5 hours', '6-Apr',
       '8-Jul', '6 hours ', '8 hours or less', '6 tiếng', '7 hours',
       '6 maybe 8', 'around 5 to 6 hours', '6h30', '7 or 8', '7-8h',
       '6 hours', '8 hour', '7.5',
       '5 hours (before phase 1 now i can control it to 7 hours)',
       '4 hours at night, 1 - 2 hours during day (after classes)', '7hrs',
       '15', '5 hours ', '8h+', '6 hrs', '8h', '8h/ day', '6.5'],
      dtype=object)

In [83]:
import re

def sleep_time_extract(value):
    """
    Extract numbers from a string, return the number if single,
    or the average if multiple numbers are found.
    """
    # Find all numbers in the string
    numbers = list(map(float, re.findall(r'\d+(?:\.\d+)?', value)))
    
    if not numbers:  
        return None
    elif len(numbers) == 1:  
        return numbers[0]
    else:  
        return sum(numbers) / len(numbers)

In [84]:
#remove hour and hours in sleep_time column
data['sleep_time'] = data['sleep_time'].apply(sleep_time_extract).astype(float)

In [85]:
data['sleep_time'] = data['sleep_time'].apply(scaling_for_days).astype(float)

In [86]:
# outlier 25 hours but we will keep it for later preprocessing
data['sleep_time'].unique()

array([7.        , 6.        , 5.        , 4.        , 6.5       ,
       3.        , 5.5       , 4.5       , 4.33333333, 2.33333333])

In [87]:
data['sleep_time'].value_counts()

sleep_time
7.000000    81
6.000000    47
5.000000    21
4.000000     6
6.500000     5
3.000000     3
5.500000     3
4.500000     1
4.333333     1
2.333333     1
Name: count, dtype: int64

### How would you rate your overall stress level in the past month?   

In [88]:
#already cleaned
data['stress_level'].unique()

array([3, 2, 5, 1, 4], dtype=int64)

### How many days in a week do you feel overwhelmed or anxious due to academic responsibilities?

In [89]:
data['stress_days_per_week'].unique()

array(['7', '0', 'Around 5 days a week', '2', '5', '3-4 days', '1',
       '3 days/ week',
       'Usually none, depends if its the finals/mid term usually 3-4 days or just a normal week probably 1 day or none',
       '7-Jun', 'every day', 'maybe not', '3', '3 days', '1 to 2 days',
       '6', '7-Jul', 'The whole week', '4', '8', '4-5 days', '2 days',
       '10 days', 'Yes but not to much ', 'Không ngày nào',
       'Everyday of the week ',
       "8 days (It's 7 days but someday I double the stress)", '3-Feb',
       'rarely any', 'all week', 'everyday', 'Cả ngày', 'All', 'About 3',
       nan, '4-Feb', 'around 5', '0 xD ', '2 or 3 days', '1 or 2 days',
       '5 days', 'idk', '5 days (monday to friday)', '1 or 2',
       'once a week', '4 days', '4-Mar', 'At least 3', '5-Apr'],
      dtype=object)

In [90]:
def stress_days_extract(value):
    """
    Extract numbers from a string, return the number if single,
    or the average if multiple numbers are found. Handles phrases like
    'every day', 'all week', etc., which correspond to specific numbers.
    """
    
    # Normalize the input string to lowercase
    value_lower = value.lower() if isinstance(value, str) else ""
    
    # Check if the value matches any predefined phrases
    for phrase, num in phrase_to_number.items():
        if phrase in value_lower:
            return num
    
    # Find all numbers in the string
    numbers = list(map(float, re.findall(r'\d+(?:\.\d+)?', value_lower)))
    
    if not numbers: 
        return None
    elif len(numbers) == 1:  
        return numbers[0]
    else:  
        return sum(numbers) / len(numbers)

In [91]:
data['stress_days_per_week'] = data['stress_days_per_week'].apply(stress_days_extract).astype(float)

In [92]:
data['stress_days_per_week'].unique()

array([ 7. ,  0. ,  5. ,  2. ,  3.5,  1. ,  3. ,  1.5,  6. ,  4. ,  8. ,
        4.5, 10. ,  7.5,  nan,  2.5])

In [93]:
data['stress_days_per_week'] = data['stress_days_per_week'].apply(scaling_for_days).astype(float)

In [94]:
data['stress_days_per_week'].value_counts()

stress_days_per_week
2.0    32
7.0    29
5.0    29
3.0    24
0.0    18
1.0    13
4.0    12
1.5     3
6.0     3
3.5     2
4.5     1
2.5     1
Name: count, dtype: int64

### How many times per week do you engage in physical exercise (e.g., walking, running, sports)?

In [95]:
data['exe_day_per_week'].unique()

array(['1', '5', '0', '5-6 times ', '3', 'None ', '6', 'Walking ', '2',
       'twice a week', 'Monday to friday (walking)', 'every day',
       '4 times', '4', '7', 'No time for such things',
       'I just walk around the campus. About an hour a day',
       '4 to 5 days ', '150 min', '1 to 2 times', '5-6 times per week',
       '5 days a week (running)', '3 hours and 30 minutes', '-100',
       '6-May', '2 times', '7 hours', nan, 'Everyday ', '5 days/week',
       '2-Jan', '3 times a week', '4 day a week', '4-Mar',
       'approximately 7 times, once per day',
       'During phase 1 of my first year, I worked out every day. In phase 2, due to a tight schedule and a lot of assignments, I could only work out 1-2 days a week.',
       '5 times a week', '2 days', '3.5 hours', '2 lần', 'Around 8 hours',
       'Mostly everyday', 'walking', '1-2 days', 'around 3', '1 hour',
       '1 (dancing)', '1 time',
       '5 (if walking to the univresity also counts)', '3 time',
       '2-4 times o

In [96]:
def exe_days_extract(value):
    """
    Extract numbers from a string, return the number if single,
    or the average if multiple numbers are found. Handles phrases like
    'every day', 'all week', etc., which correspond to specific numbers.
    """
    
    # Normalize the input string to lowercase
    value_lower = value.lower().strip() if isinstance(value, str) else ""
    
    
    # Find all numbers in the string
    numbers = list(map(float, re.findall(r'\d+(?:\.\d+)?', value_lower)))
    
    
    # Check if the value matches any predefined phrases
    for phrase, num in phrase_to_number.items():
        if phrase in value_lower:
            numbers.append(num)
    
    
    if not numbers: 
        return None
    elif len(numbers) == 1:  
        return numbers[0]
    else:  
        return sum(numbers) / len(numbers)

In [97]:
data['exe_day_per_week'] = data['exe_day_per_week'].apply(exe_days_extract).astype(float)

In [98]:
data['exe_day_per_week'].unique()

array([  1.        ,   5.        ,   0.        ,   5.5       ,
         3.        ,   6.        ,   2.        ,   7.        ,
         4.        ,          nan,   4.5       , 150.        ,
         1.5       ,  16.5       , 100.        ,   2.6       ,
         3.5       ,   8.        ,   2.5       ,   2.33333333,
        48.        ])

In [99]:
data['exe_day_per_week'] = data['exe_day_per_week'].apply(scaling_for_days)

In [100]:
data['exe_day_per_week'].unique()

array([1.        , 5.        , 0.        , 5.5       , 3.        ,
       6.        , 2.        , 7.        , 4.        ,        nan,
       4.5       , 1.5       , 2.6       , 3.5       , 2.5       ,
       2.33333333])

### filling nan value

In [101]:
# Extract to other dataframe first
columns_to_extract = data.columns[[num for num in range(4)]]
df1 = data[columns_to_extract]
df1.head()

sleep_time  stress_level  stress_days_per_week  exe_day_per_week
0         7.0             3                   7.0               1.0
1         7.0             2                   0.0               5.0
2         6.0             5                   5.0               0.0
3         7.0             2                   2.0               5.5
4         7.0             1                   0.0               3.0

In [102]:
df1 = df1.fillna(df1.mean())

In [103]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   sleep_time            169 non-null    float64
 1   stress_level          169 non-null    int64  
 2   stress_days_per_week  169 non-null    float64
 3   exe_day_per_week      169 non-null    float64
dtypes: float64(3), int64(1)
memory usage: 5.4 KB


In [104]:
df1.describe()

sleep_time  stress_level  stress_days_per_week  exe_day_per_week
count  169.000000    169.000000            169.000000        169.000000
mean     6.196252      3.189349              3.482036          3.410634
std      0.996909      1.068880              2.230666          2.142428
min      2.333333      1.000000              0.000000          0.000000
25%      6.000000      2.000000              2.000000          2.000000
50%      6.500000      3.000000              3.000000          3.000000
75%      7.000000      4.000000              5.000000          5.000000
max      7.000000      5.000000              7.000000          7.000000

In [105]:
df1.to_csv('df1.csv')

### How many hours per week do you spend completing assignments or projects? 

In [107]:
data['assignment_hour_per_week'].unique()

array(['3', '40', 'Around 4 hours a week', '10 hours', '1', '20', '80',
       'Almost the whole day, almost every day', '50', '5-6 hours', '17',
       '2', '1-2 week', 'Probably less than 10 hours per week',
       'About 20 hours', 'minimum 60 hours per week', 'about 60 hours',
       '10', '27', '7', '8-Jun', '1h', 'more than 24 hours', '6',
       'about 15 hours', '28 to 30 hours', '8 hours each day', 'Tons',
       '60', '30', 'Approximately 10 hours per week', 'About 42 hours',
       '24', '5', '4', '5-7h', ' hours', '28', '83866262', '35', '16',
       '36-40 hours', '5 hours', 'About 50 hours', '14', '90', '55', '15',
       '2hours/day', '8', '5-Apr', 'More than 40 hours/week',
       '3 or 4 hours', '3-Feb', '4 hours', '4 hours a day', '3.5 hours',
       '1- 3 tiếng', '30 hours', '8 hours on average', 'Over 20',
       'Depend on difficulty usually around 20', '6-Apr',
       'it is around 42 hours', '21', '48 hours or more', '2-Jan',
       'Maybe 5 hours', '21 hours10',

In [109]:
def assignment_hour_extract(value):
    """
    Extract numbers from a string, return the number if single,
    or the average if multiple numbers are found. Handles phrases like
    'every day', 'all week', etc., which correspond to specific numbers.
    """
    
    # Normalize the input string to lowercase
    value_lower = value.lower().strip() if isinstance(value, str) else ""
    
    
    # Find all numbers in the string
    numbers = list(map(float, re.findall(r'\d+(?:\.\d+)?', value_lower)))
    
    
    # Check if the value matches any predefined phrases
    for phrase, num in phrase_to_number.items():
        if phrase in value_lower:
            numbers.append(num)
    
    
    if not numbers: 
        return None
    elif len(numbers) == 1:  
        return numbers[0]
    else:  
        return sum(numbers) / len(numbers)

In [110]:
data['assignment_hour_per_week'] = data['assignment_hour_per_week'].apply(assignment_hour_extract).astype(float)

In [113]:
data['assignment_hour_per_week'].unique()

array([3.0000000e+00, 4.0000000e+01, 4.0000000e+00, 1.0000000e+01,
       1.0000000e+00, 2.0000000e+01, 8.0000000e+01, 7.0000000e+00,
       5.0000000e+01, 5.5000000e+00, 1.7000000e+01, 2.0000000e+00,
       1.5000000e+00, 6.0000000e+01, 2.7000000e+01, 8.0000000e+00,
       2.4000000e+01, 6.0000000e+00, 1.5000000e+01, 2.9000000e+01,
                 nan, 3.0000000e+01, 4.2000000e+01, 5.0000000e+00,
       2.8000000e+01, 8.3866262e+07, 3.5000000e+01, 1.6000000e+01,
       3.8000000e+01, 1.4000000e+01, 9.0000000e+01, 5.5000000e+01,
       3.5000000e+00, 1.3500000e+01, 2.1000000e+01, 4.8000000e+01,
       1.5500000e+01, 1.4500000e+01, 1.1200000e+02, 0.0000000e+00,
       2.5000000e+01, 1.1000000e+01, 4.5000000e+01, 1.2000000e+01,
       9.5000000e+00, 1.9000000e+01, 1.8500000e+01])

In [115]:
data['assignment_hour_per_week'] = data['assignment_hour_per_week'].apply(scaling_for_hours_week).astype(float)

In [116]:
data['assignment_hour_per_week'].unique()

array([  3. ,  40. ,   4. ,  10. ,   1. ,  20. ,  80. ,   7. ,  50. ,
         5.5,  17. ,   2. ,   1.5,  60. ,  27. ,   8. ,  24. ,   6. ,
        15. ,  29. ,   nan,  30. ,  42. ,   5. ,  28. , 168. ,  35. ,
        16. ,  38. ,  14. ,  90. ,  55. ,   3.5,  13.5,  21. ,  48. ,
        15.5,  14.5, 112. ,   0. ,  25. ,  11. ,  45. ,  12. ,   9.5,
        19. ,  18.5])

In [117]:
data['assignment_hour_per_week'].value_counts()

assignment_hour_per_week
20.0     17
10.0     15
4.0      11
5.0      11
30.0     11
3.0      10
40.0      8
8.0       6
15.0      6
6.0       6
2.0       4
14.0      4
24.0      4
7.0       4
60.0      3
25.0      3
35.0      3
1.0       3
17.0      2
3.5       2
16.0      2
11.0      2
80.0      2
42.0      2
50.0      2
21.0      2
45.0      1
15.5      1
19.0      1
12.0      1
0.0       1
112.0     1
9.5       1
14.5      1
28.0      1
48.0      1
13.5      1
55.0      1
90.0      1
38.0      1
168.0     1
29.0      1
27.0      1
1.5       1
5.5       1
18.5      1
Name: count, dtype: int64

### How many exams or tests do you typically have in a month?

In [120]:
data['num_exams_month'].unique()

array(['3', '0.56', '4', '3-Feb', '1', '2-Jan', 'Maybe 3-4', '2',
       '2 tests/ month', 'One to none because its my first year',
       '1 or 2',
       'once every week since i also take part in many courses outside university',
       '5', 'Currently, 1 to 2', '1 to 2 ', 'an exam every 2 weeks',
       'Depend', '2 exams', 'Maybe 4 hours', '199',
       'Many subjects have assignments at the same time for many months',
       'One', '10', '9-Jul', 'Assignments every week ',
       'In exam season, usually 3 exams/week. Generally, I took other outside course modules so around 5-6 per month.',
       '2 tests', '0', '3-4 exams in a month',
       'almost none accept finals and projects', 'Thi 5 môn/ tháng',
       '2 or 3', '4-Mar', 'only mid term', 'maybe 12 ', '1-2 tests',
       'none', '5 tests', '2-5 homeworks',
       'For the 1st semester, I have had any exam untill now, but I have 1-2 presentations every week',
       '1 test', '3 (math exam, ielts and academic)', 'depends',

In [121]:
def exams_month_extract(value):
    """
    Extract numbers from a string, return the number if single,
    or the average if multiple numbers are found. Handles phrases like
    'every day', 'all week', etc., which correspond to specific numbers.
    """
    
    # Normalize the input string to lowercase
    value_lower = value.lower().strip() if isinstance(value, str) else ""
    
    
    # Find all numbers in the string
    numbers = list(map(float, re.findall(r'\d+(?:\.\d+)?', value_lower)))
    
    
    # Check if the value matches any predefined phrases
    for phrase, num in phrase_to_number.items():
        if phrase in value_lower:
            numbers.append(num)
    
    
    if not numbers: 
        return None
    elif len(numbers) == 1:  
        return numbers[0]
    else:  
        return sum(numbers) / len(numbers)

In [122]:
data['num_exams_month'] = data['num_exams_month'].apply(exams_month_extract).astype(float)

In [123]:
data['num_exams_month'].unique()

array([  3.        ,   0.56      ,   4.        ,   1.        ,
         2.        ,   3.5       ,   0.        ,   1.5       ,
                nan,   5.        , 199.        ,  10.        ,
         9.        ,   5.25      ,   2.5       ,  12.        ,
         1.33333333,   0.5       ])

In [125]:
data['num_exams_month'] = data['num_exams_month'].apply(scaling_for_exams_month).astype(float)

In [126]:
data['num_exams_month'].unique()

array([ 3.        ,  0.56      ,  4.        ,  1.        ,  2.        ,
        3.5       ,  0.        ,  1.5       ,         nan,  5.        ,
       36.        , 10.        ,  9.        ,  5.25      ,  2.5       ,
       12.        ,  1.33333333,  0.5       ])

In [127]:
data['num_exams_month'].value_counts()

num_exams_month
1.000000     50
2.000000     41
3.000000     22
4.000000     11
0.000000      9
1.500000      7
5.000000      5
3.500000      4
2.500000      2
12.000000     2
0.560000      1
36.000000     1
10.000000     1
9.000000      1
5.250000      1
1.333333      1
0.500000      1
Name: count, dtype: int64

### How would you describe the difficulty level of your current coursework?

In [131]:
data['difficulty_level'].unique()

array([3, 2, 5, 1, 4], dtype=int64)

### How many hours do you spend each week managing academic deadlines?

In [133]:
data['hours_spend_projects'].unique()

array(['7', '30', 'Roughly 10 hours', '2 hours', '3', '20', '50',
       '3-4 hours', '1', '14', '5', '6', 'minimum 60 hours per week',
       '1hours', '120', '2', '3h', '28', '10', '3 to 4 hours', '56',
       'Depends', '60', '1 hour', '24', '12', nan, '8', '2424', '16',
       'I dont get the point of the question, its the same with above question',
       '7 hours', '80', '16*7 hours', '87', '0', '2hours/day ',
       'More than 40 hours/week', '4 hours', '17', '5-Mar', '4', '15',
       '30 mins/ week', '4 hours per week or more', '1 hour 15 minutes ',
       '3.5 hours', '1 tiếng', 'Around 10 hours', 'Over 10',
       'Around 5 to 8', "i don't knwo", '20 hours', '10 hours', '21',
       'around 48 hours', '0 xDDDDDD', 'about 20 hours', '7-May',
       '24 hours', "I don't get this question", 'variety', '40',
       'more than 6 hours', '55', 'Unsure', 'Not much really', '48',
       '2 hours each week', '16 hours ', '2hrs', '3 hours', '10h+',
       'Around 30', 'Over 24 hours',

In [136]:
def hours_deadline_extract(value):
    """
    Extract numbers from a string, return the number if single,
    or the average if multiple numbers are found. Handles phrases like
    'every day', 'all week', etc., which correspond to specific numbers.
    """
    
    # Normalize the input string to lowercase
    value_lower = value.lower().strip() if isinstance(value, str) else ""
    
    
    # Find all numbers in the string
    numbers = list(map(float, re.findall(r'\d+(?:\.\d+)?', value_lower)))
    
    
    # Check if the value matches any predefined phrases
    for phrase, num in phrase_to_number.items():
        if phrase in value_lower:
            numbers.append(num)
    
    
    if not numbers: 
        return None
    elif len(numbers) == 1:  
        return numbers[0]
    else:  
        return sum(numbers) / len(numbers)

In [137]:
data['hours_spend_projects'] = data['hours_spend_projects'].apply(hours_deadline_extract).astype(float)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'